const express = require('express')
const cron=require('node-cron')
const scripts=require('./scripts/scripts')
const path=require('path')
const morgan=require('morgan')
const methodOverride = require('method-override')
const app= express()
const indexRouter=require('./routes/index')
const estudianteRouter=require('./routes/estudiantesRouter')
const profesoresRouter=require('./routes/profesoresRouter')
//const materiasRouter=require('./routes/materiasRouter')

//app.set('views',path.join(__dirname,'views'))
//app.set('view engine','ejs')

cron.schedule('0 0 * * *',function(){
    scripts.adddia()
    .then(console.log('Día añadido a la base de datos'))
})
app.use(morgan('dev'))
app.use(express.json())
app.use(express.static(path.resolve(__dirname,'../public')))
app.use(express.urlencoded({extended: false}))
app.use(methodOverride('_method'))

app.use('/',indexRouter)
app.use(estudianteRouter)
//app.use(materiasRouter)
app.use(profesoresRouter)

app.listen(1337,()=>console.log('Servidor corriendo en el puerto 1337'))