var express = require('express')
var router=express.Router()
const estudiantesController=require('../controllers/estudiantesController')
router.get('/estudiantes',estudiantesController.list)
router.get('/estudiantes/login',estudiantesController.login)
router.post('/estudiantes/create',estudiantesController.create)
router.get('/estudiantes/detail',estudiantesController.detail)
router.put('/estudiantes/update',estudiantesController.update)
router.put('/estudiantes/delete',estudiantesController.delete)
module.exports=router