var express = require('express')
var router=express.Router()
const profesoresController=require('../controllers/profesoresController')
router.get('/profesores',profesoresController.list)
router.get('/profesores/login',profesoresController.login)
router.post('/profesores/create',profesoresController.create)
router.get('/profesores/detail',profesoresController.detail)
router.put('/profesores/update',profesoresController.update)
router.put('/profesores/delete',profesoresController.delete)
module.exports=router